<aside class="asideContainer">

    <div class="item">
        <h2><a href="http://www.bbc.co.uk/learningenglish/english/features/6-minute-english">
                English Lishtening</a></h2>
        <audio controls="controls">                        
            <source src="audio/englishListening.mp3" type="audio/mpeg"/>
            English Listening.
        </audio> 
    </div>
    <hr />
    <div class="item">
            <h2> Favourit Courses</h2>
        <ol>
            <li> <a href="default.html">English course</a></li>
            <li> <a href="default.html">Network Administration</a> </li>
            <li> <a href="default.html">CCNA Part 1 </a></li>
            <li> <a href="default.html">CCNA Part 2 </a></li>
            <li> <a href="default.html">CCNP Part 1 </a></li>
            <li> <a href="default.html">CCNP Part 2 </a></li>
            <li> <a href="default.html">Programing with Python </a></li>
            <li> <a href="default.html">Creating Web Application</a> </li>
            <li> <a href="default.html">HTML and CSS </a></li>
            <li> <a href="default.html">JavaScript </a></li>
            <li> <a href="default.html">PHP </a></li>
        </ol>
    </div>
    <hr />
    <div class="item">
            <h2> Job opportunities</h2>
            <ul>
                <li><a href="jobs.html#network_admin">Network Administrator</a></li>
                <li><a href="jobs.html#web_design"> Web designer</a></li>
                <li><a href="jobs.html#data_admin">Database Administrator</a></li>
            </ul>
    </div>                    
                
              
</aside>  