<header id="header">
            <div id="top_panel">
                <div id="logo">
                    <img src="images/logo.png" alt="Ulearn Logo"/>
                </div>
                <div class="top_panel">
                    <label for="search" class="search">&#160;&#160;&#160; Search
                        <input type="search" name="search" id="search"/>
                    </label>
                    <div class="top_item">
                        <label class="course_login">
                            <select>
                                <option value="0" selected="selected">Courses </option>
                                <option value="c1">Course 1</option>
                                <option value="c2">Course 2</option>
                                <option value="c3">Course 3</option>
                                <option value="c4">Course 4</option>
                                <option value="c5">Course 5</option>
                                <option value="c6">Course 6</option>
                                <option value="c7">Course 7</option>
                            </select>
                        </label>
                        
                        <label class="course_login"><a href="default.html">Login</a></label>
                    </div>
                </div>
            </div>
            <!--Area1: for menues: Home, Blog, Career, About-->
            <nav id="nav">
                <div class="menu" id="menu">
                    
                    <a href="index.html" class="hover">Home</a>
                    <a href="default.html" class="hover">Courses</a>
                    <a href="default.html" class="hover">Students</a>
                    <a href="default.html" class="hover">instructors</a>
                    <a href="default.html" class="hover">Blog</a>
                    <a href="jobs.html" class="hover">Jobs</a>
                    <a href="apply.html" class="hover">Job Apply</a>
                    <a href="about.html" class="hover">About</a>
                   
                </div>
                <div id="slogan">
                    <h1>Larn your way at Ulearn.</h1>  
                </div>              
            </nav>
</header> 